<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "stomt_feedback"
 *
 * Auto generated by Extension Builder 2017-07-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Stomt-Feedback',
    'description' => 'STOMT makes it easy for anyone to provide instant feedback. This plugin allows you to customize the STOMT feedback button and add it to your typo3 site.',
    'category' => 'plugin',
    'author' => 'STOMT Gmbh.',
    'author_email' => 'bader.mariem1@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.99-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
