<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "stomt_feed"
 *
 * Auto generated by Extension Builder 2018-03-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'STOMTFEEDBACK',
    'description' => 'tttttttttttttttttttttttttttttttt',
    'category' => 'plugin',
    'author' => 'Mariem Bader',
    'author_email' => 'bader.mariem1@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
